version: '3.8'

services:
    bot:
        build: ./
        restart: always
        env_file:
            - ./docker/app-variables.env
        depends_on:
            - postgres
    postgres:
        image: postgres:14.4
        restart: always
        env_file:
            - ./docker/app-variables.env
