"""file id

Revision ID: 002
Revises: 001
Create Date: 2024-01-07 06:13:40.238718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprompt', sa.Column('file_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'userprompt', ['file_id'])
    op.create_unique_constraint(None, 'userprompt', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprompt', type_='unique')
    op.drop_constraint(None, 'userprompt', type_='unique')
    op.drop_column('userprompt', 'file_id')
    # ### end Alembic commands ###
